### ISSUE TITLE
Common.GitHub.proj sets GitHubProject to Corvus.Extensions

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Leasing#1]
This:

```xml
<GitHubProject>Corvus.Extensions</GitHubProject>
```

at https://github.com/corvus-dotnet/Corvus.Leasing/blob/master/Solutions/Common.GitHub.proj#L4 is presumably a cut and paste error.

**Comment by mwadams** [comment]
@HowardvanRooijen Is this still an issue?

**Comment by HowardvanRooijen** [comment]
It's just been fixed on the external-pipelines branch
